spring:
  h2:
    console:
      enabled: true
  datasource:
    initialization: embedded
    url: jdbc:h2:mem:devdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-dll: true
    hibernate:
      ddl-auto: create-drop
